platform :ios, '9.0'

use_frameworks!

link_with 'Circator', 'CircatorKit'

pod 'ResearchKit', :git => 'https://github.com/DJBen/ResearchKit.git'
pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
pod 'Charts', :git => 'https://github.com/danielgindi/ios-charts.git'
pod 'Alamofire', '~> 2.0'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'SwiftDate'
pod 'SwiftyUserDefaults'
pod 'SwiftyBeaver', '~> 0.2'
pod 'Dodo', '~> 2.0'
pod 'CryptoSwift'
pod 'AsyncSwift'
pod 'Locksmith'
pod 'Granola', :git => 'https://github.com/yanif/Granola.git'
pod 'Stormpath'
pod 'Former'
pod 'HTPressableButton'
pod 'MGSwipeTableCell'
pod 'Pages'
